[package]
name = "nn_layers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix_operations = { path = "../matrix_operations" }
model = { path = "../model" }
num = "0.4.0"